BAck to Python to deal with "Handling Exceptions!"
